### ISSUE TITLE
Prepare test data

### ISSUE THREAD

**Issue by netzwerg** [fhnw-saav/saav#22]
In addition to random mock data, we need data useful for testing (on all levels: automatic/manual, calculations/UI).

Specifically, we need an analysis which:
- Contains a reasonable category/sub-category/indicator structure
- Contains non-random values and weights (for various entities)

Based on this analysis, we need formulated expectations:
- Expected values and UI state after import
- Expected UI state after selection/color/pinning changes
- Expected values and UI state after weight changes

**Comment by biomed23** [comment]
- Created the student project test data and translated it to English
- Added the original Excel to the repo and tested the aggregation and computations for sp02 (see respective section in the Excel file)
