### ISSUE TITLE
Support pinning of sub-criteria

### ISSUE THREAD

**Issue by netzwerg** [fhnw-saav/saav#56]
Allowing to pin a sub-criteria axis (via mouse click) makes the displayed indicators persistently visible. This e.g. allows to make truncated indicator labels visible via hovering (currently, these labels cannot be hovered because they only appear if a sub-criteria is hovered)

**Comment by netzwerg** [comment]
From an HCI perspective, this turns out to more complex than anticipated: How do we handle a case where one sub-criteria axis is pinned and another one is hovered? For which one do we display indicators? cc @biomed23

**Comment by biomed23** [comment]
I usually handle this by just giving precedence to pinning (selection). If something is pinned (selected) then hovering (probing) is ignored, i.e. I would still highlight the axis slightly if it is probed to show that something will happen if one clicks, but the additional information is not shown. It is stable for the selected one.

**Comment by netzwerg** [comment]
After further discussion, we decided against this feature because it would make the UI interaction concepts less intuitive. Instead, we want to address the underlying problem (indicator labels being too long) by giving the indicator component more horizontal space.
