### ISSUE TITLE
Handle corner cases in charts

### ISSUE THREAD

**Issue by netzwerg** [fhnw-saav/saav#63]
- [x]  Handle missing values (see `computeAxisValue` in `QualityChartComponent` and `computeRadius` in `ProfileChartComponent`)
- [x]  Handle degenerate case of single (sub)criteria (display small dash?)

**Comment by biomed23** [comment]
There is a small issue remaining when trying to probe a value that is isolated (no other values to the right or left). In that case that value does not react to probing as the current hit algorithm relies on there being a neighbor present. It is not impossible to fix that but would be quite an effort. It is probably a rare case and we therefore leave it as a feature until it is reported as a bug.
