### ISSUE TITLE
Generalize usability of SAAV even further

### ISSUE THREAD

**Issue by netzwerg** [fhnw-saav/saav#83]
Thanks to #82 ("Generalize usability of SAAV"), the application can now be used for all kinds of catalogs and input data.

However, concepts like the project/person/organisation distinction are still baked directly into the application.

We could get rid of this through the following changes:

* Configure title as part of JSON config
* Configure allowed value range as part of JSON config
* Fallback to reasonable defaults if no JSON config is specified

**Comment by netzwerg** [comment]
Done.

**Comment by netzwerg** [comment]
@markus-d Could you please extend your python script to include `title` and `allowedValueRange`? See e.g. https://github.com/fhnw-saav/saav/blob/43502fff2d26fc45a94731a8349c09964f8ded4e/config/projects.json

**Comment by markus-d** [comment]
Done.
